Repository sourcecred/sourcecred, pull requests merged in 2018-09, with the labels that each got.

#764 Fix a bug that can lock the cred explorer UI
  src/app/credExplorer/App.js
  src/app/credExplorer/App.test.js
  src/app/credExplorer/state.js
  src/app/credExplorer/state.test.js
Labels: bug

#768 webpack: empty build dir instead of removing it
  config/RemoveBuildDirectoryPlugin.js
  package.json
Labels: build

#770 Rename `makeWebpackConfig` to `webpack.config.web`
  config/webpack.config.web.js
  package.json
Labels: build

#766 babel: transform ES6 modules to CommonJS
  config/babel.js
Labels: build

#774 backend: remove superfluous file existence check
  scripts/backend.js
Labels: build

#773 Organize weights by plugin
  CHANGELOG.md
  src/app/credExplorer/App.js
  src/app/credExplorer/WeightConfig.js
  src/app/credExplorer/weights/PluginWeightConfig.js
  src/app/credExplorer/weights/PluginWeightConfig.test.js
Labels: frontend

#779 backend: export a normal Webpack config object
  config/webpack.config.backend.js
  scripts/backend.js
Labels: build

#781 backend: set Babel flags in Webpack config
  config/webpack.config.backend.js
Labels: build

#782 backend: invoke Webpack directly in package script
  config/test.js
  package.json
  scripts/backend.js
Labels: build

#784 test: invoke `yarn backend` only once
  config/test.js
  scripts/build_static_site.sh
  sharness/test_build_static_site.t
  src/plugins/git/loadRepositoryTest.sh
  src/plugins/github/fetchGithubRepoTest.sh
Labels: build

#785 Add `weightsToEdgeEvaluator`
  src/app/credExplorer/WeightConfig.js
  src/app/credExplorer/edgeWeights.js
  src/app/credExplorer/weights/weightsToEdgeEvaluator.js
  src/app/credExplorer/weights/weightsToEdgeEvaluator.test.js
Labels: frontend

#803 test: invoke Jest in CI mode
  config/test.js
Labels: build

#856 Improve CI performance by limiting max workers
  config/test.js
Labels: build

#864 travis: fix notification email config
  .travis.yml
Labels: build

#866 prettier: ignore sharness/
  .prettierignore
Labels: build

#867 travis: pin Node v8.x.x
  .travis.yml
Labels: build
