Repository sourcecred/sourcecred, pull requests merged in 2020-09, with the labels that each got.

#2076 jsonLog: update documentation about serialized form
  src/util/jsonLog.js
Labels: documentation

#2215 disable esModules in css-loader
  config/webpack.config.web.js
Labels: build

#2251 Fix white-on-white text in alpha subpanel
  src/ui/components/Explorer/Explorer.js
Labels: bug, frontend
