Repository sourcecred/sourcecred, pull requests merged in 2020-03, with the labels that each got.

#1684 github: fix stack overflow in `RelationalView`
  src/plugins/github/relationalView.js
  src/plugins/github/relationalView.test.js
Labels: bug

#1685 github: use plaintext owner and name in cache key
  src/plugins/github/cacheId.js
  src/plugins/github/cacheId.test.js
Labels: enhancement

#1728 Discord: add developer notes to the README
  src/plugins/discord/README.md
Labels: documentation
