Repository sourcecred/sourcecred, pull requests merged in 2020-10, with the labels that each got.

#2291 Set default period if it doesn't exist in dependenciesConfig
  sharness/__snapshots__/test-instance/config/dependencies.json
  src/api/dependenciesConfig.js
  src/api/dependenciesConfig.test.js
Labels: approved with suggestions

#2335 Implement MVP of Ledger History Viewer
  src/ui/components/AdminApp.js
  src/ui/components/LedgerViewer.js
  src/ui/components/Menu.js
  src/ui/utils/dateHelpers.js
Labels: approved with suggestions

#2338 Remove _getProjectIds.js
  src/core/_getProjectIds.js
Labels: ready for review

#2334 Improve Ledger Admin UX
  src/ui/components/AliasView.js
  src/ui/components/IdentityMerger.js
  src/ui/components/LedgerAdmin.js
  src/ui/components/Menu.js
Labels: approved

#2328 Fix random number generation in API build
  config/webpack.config.api.js
Labels: approved

#2344 Delete publish workflow
  .github/workflows/publish.yml
Labels: ready for review

#2349 Version 0.7.1
  package.json
Labels: priority, ready for review

#2284 Refactor Explorer to Functional Components
  src/ui/components/AdminApp.js
  src/ui/components/Explorer/Explorer.js
  src/ui/components/Explorer/ExplorerApp.js
Labels: ready for review

#2356 Implement viewer for Grain Distributions
  src/ui/components/AdminApp.js
  src/ui/components/LedgerViewer.js
Labels: ready for review

#2266 Implement TaskManager
  src/util/taskManager.js
  src/util/taskManager.test.js
  src/util/taskReporter.js
Labels: ready for review

#2365 MPG: Expose node and edge order
  src/core/credGraph.js
  src/core/markovProcessGraph.js
  src/core/markovProcessGraph.test.js
Labels: ready for review

#2367 pull MarkovNode and MarkovEdge into new modules
  src/core/credrank/credGraph.js
  src/core/credrank/markovEdge.js
  src/core/credrank/markovNode.js
  src/core/credrank/markovProcessGraph.js
  src/core/credrank/markovProcessGraph.test.js
Labels: ready for review

#2368 credrank: factor out node gadgets
  src/core/credrank/compute.js
  src/core/credrank/credGraph.js
  src/core/credrank/markovProcessGraph.js
  src/core/credrank/markovProcessGraph.test.js
  src/core/credrank/nodeGadgets.js
Labels: ready for review

#2370 credrank: factor out radiation edge gadgets
  src/core/credrank/edgeGadgets.js
  src/core/credrank/markovProcessGraph.js
  src/core/credrank/markovProcessGraph.test.js
Labels: ready for review

#2374 credrank: create a payout gadget
  src/core/credrank/credGraph.js
  src/core/credrank/edgeGadgets.js
  src/core/credrank/markovProcessGraph.js
  src/core/credrank/markovProcessGraph.test.js
Labels: ready for review

#2375 credrank: factor out webbing gadget
  src/core/credrank/edgeGadgets.js
  src/core/credrank/markovProcessGraph.js
  src/core/credrank/markovProcessGraph.test.js
Labels: ready for review

#2376 credrank: gadgets track participants by id
  src/core/credrank/credGraph.js
  src/core/credrank/edgeGadgets.js
  src/core/credrank/markovProcessGraph.js
  src/core/credrank/markovProcessGraph.test.js
  src/core/credrank/nodeGadgets.js
Labels: ready for review

#2383 Fix CredRank JSON serialization
  src/core/credrank/markovProcessGraph.js
  src/core/credrank/markovProcessGraph.test.js
Labels: ready for review

#2398 WeightConfig: fix “Node weights” typo
  src/ui/weights/WeightConfig.js
Labels: bug, frontend, ready for review

#2384 Virtualize the seed node
  src/core/credrank/markovProcessGraph.js
Labels: ready for review

#2385 credrank: virtualize the epoch accumulators
  src/core/credrank/markovProcessGraph.js
Labels: ready for review

#2386 credrank: virtualize participant epochs
  src/core/credrank/markovProcessGraph.js
Labels: ready for review

#2387 credrank: make parameters accessible on MPG
  src/core/credrank/markovProcessGraph.js
  src/core/credrank/markovProcessGraph.test.js
Labels: ready for review

#2418 Eth Plugin: Create the EthAddress type and helpers
  src/plugins/ethereum/ethAddress.js
  src/plugins/ethereum/ethAddress.test.js
Labels: ready for review

#2431 Update max name length to 42 chars
  src/core/identity/name.js
  src/core/identity/name.test.js
Labels: ready for review

#2419 Eth Plugin: Scaffolding
  src/plugins/ethereum/createIdentities.js
  src/plugins/ethereum/declaration.js
  src/plugins/ethereum/ethAddressNode.js
  src/plugins/ethereum/ethAddressNode.test.js
  src/plugins/ethereum/plugin.js
Labels: ready for review

#2428 Bugfix: Remove Hardcoded Grain from Accounts Overview
  src/ui/components/AccountOverview.js
Labels: ready for review

#2439 api: fix Observable compatibility
  config/webpack.config.api.js
  package.json
  src/util/getRandomValues.js
  src/util/getRandomValues.test.js
  src/util/uuid.js
  yarn.lock
Labels: build
