Repository sourcecred/sourcecred, pull requests merged in 2020-11, with the labels that each got.

#2434 discord: refactor and test reaction weight logic
  src/plugins/experimental-discord/config.js
  src/plugins/experimental-discord/config.test.js
  src/plugins/experimental-discord/createGraph.js
  src/plugins/experimental-discord/plugin.js
  src/plugins/experimental-discord/reactionWeights.js
  src/plugins/experimental-discord/reactionWeights.test.js
Labels: ready for review

#2456 Added compareGraphs method
  src/core/graph.js
  src/core/graph.test.js
Labels: ready for review

#2467 v0.7.2
  package.json
Labels: priority

#2389 Add pagination to LedgerViewer
  src/ui/components/LedgerViewer.js
Labels: ready for review

#2458 Add compareWeights function
  src/core/weights.js
  src/core/weights.test.js
Labels: ready for review

#2468 Discord: Refactor createGraph
  src/plugins/experimental-discord/createGraph.js
Labels: ready for review

#2466 add description and timestamp to nodeToString
  src/core/graph.js
  src/core/graph.test.js
Labels: ready for review

#2489 Refactor compareGraphs to match compareWeights
  src/core/graph.js
  src/core/graph.test.js
Labels: ready for review

#2457 cli: Add -d diff flag to graph command
  src/cli/common.js
  src/cli/graph.js
  src/core/weights.js
Labels: ready for review

#2485 Add prompt if no plugins are configured
  src/cli/load.js
Labels: approved

#2504 Implement function for diffing event histories of two Ledgers
  package.json
  src/core/ledger/diffLedger.js
  src/core/ledger/diffLedger.test.js
  yarn.lock
Labels: ready for review

#2507 Don't reset page on # of results per page change for Ledger Viewer
  src/ui/components/LedgerViewer.js
Labels: approved

#2519 Add graph diff cmd to README
  README.md
Labels: ready for review

#2480 Implement LedgerManager class
  src/api/ledgerManager.js
  src/api/ledgerManager.test.js
Labels: ready for review

#2533 Revert "Sourcecred Gitcoin Plugin 2 (#2452)"
  package.json
  scripts/docker-entrypoint.sh
  src/api/bundledPlugins.js
  src/plugins/gitcoin/address.js
  src/plugins/gitcoin/config.js
  src/plugins/gitcoin/createGraph.js
  src/plugins/gitcoin/createIdentities.js
  src/plugins/gitcoin/declaration.js
  src/plugins/gitcoin/fetch.js
  src/plugins/gitcoin/mirrorRepository.js
  src/plugins/gitcoin/nodesAndEdges.js
  src/plugins/gitcoin/plugin.js
  yarn.lock
Labels: build

#2512 logic for Cred budgets on Weighted Graphs
  src/core/mintBudget.js
  src/core/mintBudget.test.js
Labels: ready for review

#2530 Bugfix(frontend): remove unstyled initial render
  src/ui/server.js
Labels: priority, ready for review

#2496 Add PR template
  .github/pull_request_template.md
Labels: ready for review

#2547 add support for limiting Cred minting by plugin
  src/api/pluginBudgetConfig.js
  src/cli/common.js
  src/core/mintBudget.js
Labels: priority

#2481 LedgerManager persist logic
  src/api/ledgerManager.js
  src/api/ledgerManager.test.js
  yarn.lock
Labels: approved

#2550 Ledger: add APIs for getting allocation and distribution by ID
  src/core/ledger/ledger.js
  src/core/ledger/ledger.test.js
Labels: ready for review

#2552 Refactor Credrank Testing & Test CredGraph
  src/core/credrank/credGraph.test.js
  src/core/credrank/markovProcessGraph.test.js
  src/core/credrank/testUtils.js
Labels: ready for review

#2553 Add tested support for deserializing CredGraphs
  src/cli/common.js
  src/core/credrank/credGraph.js
  src/core/credrank/credGraph.test.js
  src/core/credrank/markovNode.js
  src/core/credrank/markovProcessGraph.js
  src/core/credrank/markovProcessGraph.test.js
Labels: ready for review
