Repository sourcecred/sourcecred, pull requests merged in 2020-04, with the labels that each got.

#1720 Add a README.md for the GitHub plugin
  src/plugins/github/README.md
Labels: documentation

#1735 Identity: add user documentation to README
  src/plugins/identity/README.md
Labels: documentation

#1765 mirror: keep updating when only `typenames` remain
  src/graphql/mirror.js
  src/graphql/mirror.test.js
Labels: bug

#1769 deps: upgrade `better-sqlite3@^7.0.0`
  flow-typed/npm/better-sqlite3_vx.x.x.js
  package.json
  yarn.lock
Labels: dependencies
