Repository sourcecred/sourcecred, pull requests merged in 2020-08, with the labels that each got.

#2072 test_no_raw_anchor_elements: set off pathspecs with `--`
  sharness/test_no_raw_anchor_elements.t
Labels: build

#2075 jsonLog: use newline-delimited JSON
  src/cli/grain.js
  src/cli/graph.js
  src/cli/score.js
  src/ledger/__snapshots__/ledger.test.js.snap
  src/ledger/ledger.js
  src/ledger/ledger.test.js
  src/ui/load.js
  src/util/disk.js
  src/util/disk.test.js
  src/util/jsonLog.js
  src/util/jsonLog.test.js
Labels: enhancement

#2100 Make match alias robust and performant
  src/ui/components/AliasSelector.js
Labels: frontend

#2162 lint: disable `no-inner-declarations`
  .eslintrc.js
Labels: build
