Repository sourcecred/sourcecred, pull requests merged in 2021-01, with the labels that each got.

#2420 Eth Plugin: Update Instance Snapshot
  sharness/__snapshots__/test-instance/config/plugins/sourcecred/ethereum/ethereumAddresses.json
  sharness/__snapshots__/test-instance/data/ledger.json
  sharness/__snapshots__/test-instance/output/accounts.json
  sharness/__snapshots__/test-instance/output/credResult.json
  sharness/__snapshots__/test-instance/output/graphs/sourcecred/ethereum/graph.json
  sharness/__snapshots__/test-instance/sourcecred.json
  src/api/bundledPlugins.js
Labels: ready for review

#2532 Add TableState webutil for paginated+filtered+sorted arrays
  src/util/sortBy.js
  src/webutil/tableState.js
Labels: ready for review

#2616 Ledger table
  src/ui/components/LedgerViewer.js
  src/webutil/tableState.js
Labels: approved

#2611 cli: Add simulation flag to credrank cmd
  src/cli/credrank.js
Labels: ready for review

#2610 cli: Add simulation flag to graph cmd
  README.md
  src/cli/graph.js
Labels: ready for review

#2627 credrank: Add intervals getter to CredGraph, rename credPerEpoch to c…
  src/core/credrank/credGraph.js
  src/core/credrank/credGraph.test.js
Labels: ready for review

#2628 Allow front end to function without Cred
  src/ui/components/AdminApp.js
  src/ui/components/Explorer/Explorer.js
  src/ui/components/ExplorerHome/ExplorerHome.js
  src/ui/load.js
Labels: ready for review

#2502 Create Generic CurrencyId type
  src/core/ledger/currency.js
  src/core/ledger/currency.test.js
  src/plugins/ethereum/ethAddress.js
Labels: approved

#2623 Combined dependency bumps
  package.json
  yarn.lock
Labels: approved

#2638 Use lodash findlast and findlastindex instead of homemade util
  package.json
  src/core/mintBudget.js
  src/util/findLast.js
  src/util/findLast.test.js
  yarn.lock
Labels: ready for review

#2649 Ledger: move reuseable test code into testUtils
  src/api/ledgerManager.test.js
  src/core/ledger/diffLedger.test.js
  src/core/ledger/ledger.test.js
  src/core/ledger/testUtils.js
Labels: ready for review

#2637 Implement CredGrainView
  src/core/credGrainView.js
  src/core/credGrainView.test.js
  src/core/credrank/testUtils.js
  src/core/ledger/testUtils.js
Labels: ready for review

#2572 grain: move defaults to api/currencyConfig
  src/api/currencyConfig.js
  src/core/ledger/grain.js
Labels: approved

#2525 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved

#2657 Bugfix: Explicitly stringify Discourse CategoryIds
  src/plugins/discourse/__snapshots__/fetch.test.js.snap
  src/plugins/discourse/fetch.js
Labels: priority

#2673 Add last distribution timestamp to the AccountOverview page
  src/ui/components/AccountOverview.js
Labels: ready for review
