Repository sourcecred/sourcecred, pull requests merged in 2021-03, with the labels that each got.

#2804 ExplorerHome: fix duplicate timeline value
  src/ui/components/ExplorerHome/ExplorerTimeline.js
Labels: ready for review

#2826 Fix interval data that is being passed into ExplorerTimeline
  src/ui/components/ExplorerHome/ExplorerHome.js
Labels: priority

#2839 Credrank help cli
  src/cli/credrank.js
  src/cli/help.js
Labels: priority

#2841 Add credGraph and credrank to api build
  src/api/index.js
Labels: priority, ready for review

#2842 Credrank Migration Full Launch
  README.md
  src/cli/go.js
  src/cli/grain.js
  src/cli/help.js
  src/cli/sourcecred.js
  src/ui/components/AdminApp.js
  src/ui/components/ExplorerHome/ExplorerHome.js
  src/ui/components/Menu.js
  src/ui/load.js
Labels: priority, ready for review

#2857 Credrank Migration Clean up
  sharness/__snapshots__/test-instance/output/credResult.json
  src/analysis/__snapshots__/credResult.test.js.snap
  src/analysis/__snapshots__/pagerankNodeDecomposition.test.js.snap
  src/analysis/credData.js
  src/analysis/credData.test.js
  src/analysis/credResult.js
  src/analysis/credResult.test.js
  src/analysis/credView.js
  src/analysis/credView.test.js
  src/analysis/nodeScore.js
  src/analysis/nodeScore.test.js
  src/analysis/pagerank.js
  src/analysis/pagerankNodeDecomposition.js
  src/analysis/pagerankNodeDecomposition.test.js
  src/analysis/weightsToEdgeEvaluator.js
  src/analysis/weightsToEdgeEvaluator.test.js
  src/api/index.js
  src/cli/grain.js
  src/cli/grain2.js
  src/cli/help.js
  src/cli/score.js
  src/cli/sourcecred.js
  src/cli/sourcecred.test.js
  src/core/ledger/applyDistributions.js
  src/core/ledger/credAccounts.js
  src/ui/components/Explorer/Explorer.js
  src/ui/components/Explorer/FilterSelect.js
  src/ui/components/Explorer/FlowsRow.js
  src/ui/components/Explorer/NodeRow.js
  src/ui/components/Explorer/WeightsConfigSection.js
Labels: ready for review

#2860 Yaz/feb2021/calculate grain per interval optimization
  src/core/credGrainView.js
  src/core/credGrainView.test.js
Labels: frontend

#2873 Refactor graph CLI to use Instance and API patterns
  src/api/index.js
  src/api/instance/instance.js
  src/api/instance/localInstance.js
  src/api/main/credrank.js
  src/api/main/graph.js
  src/api/main/graph.test.js
  src/cli/common.js
  src/cli/credrank.js
  src/cli/graph.js
Labels: ready for review

#2876 Refactor grain CLI to use Instance and API patterns
  src/api/index.js
  src/api/instance/instance.js
  src/api/instance/localInstance.js
  src/api/main/grain.js
  src/api/main/graph.js
  src/cli/common.js
  src/cli/common.test.js
  src/cli/credrank.js
  src/cli/grain.js
  src/cli/graph.js
Labels: ready for review
