Repository sourcecred/sourcecred, pull requests merged in 2021-04, with the labels that each got.

#2893 Create NetworkReadInstance
  src/api/index.js
  src/api/instance/readInstance.js
  src/core/storage/networkStorage.js
  src/core/storage/networkStorage.test.js
  src/core/storage/originStorage.js
  src/core/storage/originStorage.test.js
  src/ui/load.js
Labels: ready for review

#2897 Update github access token regex
  src/plugins/github/token.js
  src/plugins/github/token.test.js
Labels: priority

#2898 Add MVP weights configuration page
  src/api/bundledDeclarations.js
  src/ui/components/AdminApp.js
  src/ui/components/Explorer/WeightsConfigSection.js
  src/ui/components/Menu.js
  src/ui/load.js
  src/ui/weights/WeightsFileManager.js
Labels: priority

#2908 Removed un-used line in graph.js to close #1598
  src/core/graph.js
Labels: good first issue

#2915 Discord: do not throw for unknown channel type
  src/plugins/discord/models.js
Labels: priority

#2508 LedgerAdmin: improve activation workflow
  src/ui/components/IdentityListItems.js
  src/ui/components/LedgerAdmin.js
Labels: ready for review

#2935 Grain: add --force flag to redo last distribution
  src/api/main/grain.js
  src/cli/credrank.js
  src/cli/grain.js
  src/core/ledger/applyDistributions.js
  src/core/ledger/applyDistributions.test.js
Labels: ready for review
